"""
Renders a solved floor plan (dict[str, Rect]) as a PNG image using matplotlib.

Run standalone:
    python -m src.visualize
This solves the example house from main.py and saves floorplan.png.
"""

import matplotlib.pyplot as plt
import matplotlib.patches as patches

# room name (or name prefix) -> color, so related rooms share a look
ROOM_COLORS = {
    "living": "#9FE1CB",
    "dining": "#9FE1CB",
    "entrance": "#9FE1CB",
    "kitchen": "#FAC775",
    "bedroom": "#AFA9EC",
    "bathroom": "#AFA9EC",
    "bath": "#AFA9EC",
}


def _color_for(name: str) -> str:
    lower = name.lower()
    for key, color in ROOM_COLORS.items():
        if lower.startswith(key):
            return color
    return "#D3D1C7"  # neutral gray fallback


def render_floorplan(plot, assignment: dict, out_path: str = "floorplan.png", title: str = "Floor plan"):
    """
    plot: Plot instance (has .width, .height)
    assignment: dict[str, Rect] as returned by FloorPlanCSPSolver.solve()
    """
    fig, ax = plt.subplots(figsize=(plot.width / 2, plot.height / 2))

    # outer plot boundary
    ax.add_patch(patches.Rectangle((0, 0), plot.width, plot.height,
                                    fill=False, edgecolor="black", linewidth=2))

    for name, rect in assignment.items():
        color = _color_for(name)
        ax.add_patch(patches.Rectangle(
            (rect.x, rect.y), rect.w, rect.h,
            facecolor=color, edgecolor="black", linewidth=1.2
        ))
        cx, cy = rect.x + rect.w / 2, rect.y + rect.h / 2
        ax.text(cx, cy, f"{name}\n{rect.area} m2", ha="center", va="center",
                fontsize=9, fontweight="bold")

    ax.set_xlim(0, plot.width)
    ax.set_ylim(0, plot.height)
    ax.set_aspect("equal")
    ax.invert_yaxis()  # so (0,0) reads top-left, like the ASCII preview
    ax.set_title(title)
    ax.set_xticks(range(0, plot.width + 1))
    ax.set_yticks(range(0, plot.height + 1))
    ax.grid(True, linewidth=0.3, alpha=0.4)

    fig.tight_layout()
    fig.savefig(out_path, dpi=150)
    plt.close(fig)
    return out_path


def render_floorplan_with_furniture(plot, assignment: dict, furniture: dict,
                                     out_path: str = "floorplan_full.png",
                                     title: str = "Floor plan with furniture"):
    """Same as render_floorplan, plus each room's placed furniture drawn
    as smaller labeled rectangles on top."""
    fig, ax = plt.subplots(figsize=(plot.width / 2, plot.height / 2))

    ax.add_patch(patches.Rectangle((0, 0), plot.width, plot.height,
                                    fill=False, edgecolor="black", linewidth=2))

    for name, rect in assignment.items():
        color = _color_for(name)
        ax.add_patch(patches.Rectangle((rect.x, rect.y), rect.w, rect.h,
                                        facecolor=color, edgecolor="black", linewidth=1.2))
        cx, cy = rect.x + rect.w / 2, rect.y + rect.h * 0.15
        ax.text(cx, cy, name, ha="center", va="center", fontsize=8, fontweight="bold")

    for room_name, items in furniture.items():
        for item in items:
            ax.add_patch(patches.Rectangle(
                (item.x, item.y), item.w, item.h,
                facecolor="white", edgecolor="#444441", linewidth=0.8, alpha=0.85
            ))
            ax.text(item.x + item.w / 2, item.y + item.h / 2, item.name,
                    ha="center", va="center", fontsize=6)

    ax.set_xlim(0, plot.width)
    ax.set_ylim(0, plot.height)
    ax.set_aspect("equal")
    ax.invert_yaxis()
    ax.set_title(title)
    ax.set_xticks(range(0, plot.width + 1))
    ax.set_yticks(range(0, plot.height + 1))
    ax.grid(True, linewidth=0.3, alpha=0.4)

    fig.tight_layout()
    fig.savefig(out_path, dpi=150)
    plt.close(fig)
    return out_path


if __name__ == "__main__":
    from .main import build_example_request
    from .csp_solver import FloorPlanCSPSolver

    request = build_example_request()
    solver = FloorPlanCSPSolver(request)
    assignment = solver.solve()
    path = render_floorplan(request.plot, assignment, out_path="floorplan.png",
                             title="Example house (auto-generated by CSP solver)")
    print(f"Saved to {path}")
